on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: exemplum.azurecr.io
        username: ${{ secrets.acr_exemplum_username }}
        password: ${{ secrets.acr_exemplum_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t exemplum.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push exemplum.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akssamples | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akssamples`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akssamples
        container-registry-url: exemplum.azurecr.io
        container-registry-username: ${{ secrets.acr_exemplum_username }}
        container-registry-password: ${{ secrets.acr_exemplum_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akssamples
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          exemplum.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
